### ISSUE TITLE
Getting a permission error when trying to build

### ISSUE THREAD

**Issue by notxt** [gt-health/PACER#16]
Hi! It's Michael from OCHIN

I'm getting a permission error in `fhir-filter` when I'm trying to run `docker-compose build`
<img width="824" alt="Screen Shot 2020-07-30 at 1 33 43 AM" src="https://user-images.githubusercontent.com/338020/88900947-ffb55f00-d204-11ea-85af-18df57f04cf0.png">

Which is odd because it doesn't look like there are any permission weirdnesses when I look at file permissions:
```
-rw-rw-r-- 1 ec2-user ec2-user  144 Jul 30 06:41 docker-compose.yml
-rw-rw-r-- 1 ec2-user ec2-user  375 Jul 30 08:29 Dockerfile
-rw-rw-r-- 1 ec2-user ec2-user  597 Jul 30 06:41 Dockerfile-SSLEnabled
-rw-rw-r-- 1 ec2-user ec2-user 1048 Jul 30 06:41 Jenkinsfile
-rw-rw-r-- 1 ec2-user ec2-user 9113 Jul 30 06:41 mvnw
-rw-rw-r-- 1 ec2-user ec2-user 5971 Jul 30 06:41 mvnw.cmd
-rw-rw-r-- 1 ec2-user ec2-user   32 Jul 30 06:41 mycertificatekeyfile.pem
-rw-rw-r-- 1 ec2-user ec2-user   47 Jul 30 06:41 mycertificate.pem
-rw-rw-r-- 1 ec2-user ec2-user 4328 Jul 30 06:41 pom.xml
-rw-rw-r-- 1 ec2-user ec2-user  459 Jul 30 06:41 README.md
-rw-rw-r-- 1 ec2-user ec2-user 7503 Jul 30 06:41 server-ssl-enabled.xml
drwxrwxr-x 4 ec2-user ec2-user   30 Jul 30 07:57 src
```

Not sure what exactly I'm missing 🤔 

Lemme know if you have any ideas. I'll take a look again in the morning and see if I can spot anything

thanks!
michael

**Comment by myungchoi** [comment]
Hi, Michael. Could you set the permission to -rwxr-xr-x for both mvnw and mvnw.cmd?

And, did you download zip file or use “git clone”?

Thanks,
Myung

**Comment by MikeRileyGTRI** [comment]
Hi Michael, as myung said, this project (fhirfilter), packages a version of the maven executable within itself, the mvnw and mvnw.cmd, they need to have executible premissions to build.

**Comment by MikeRileyGTRI** [comment]
I am having difficulty replicating the issue on my end here. Can you check these files too?
/omoponfhir-omopv5-stu3-conceptmapping-server/wait-for-it.sh
/cqlstorage/wait-for-it.sh
/jobmanagementsystem/wait-for-it.sh
/nginx-cache/wait-for-it.sh

These "wait-for-it.sh" shell scripts all do the same thing: they check that a certain service in the docker-compose environment is up and running before THEY start their runtime task. We're using this as a mechanism to make sure the database is up and running before starting services that crash if the database cannot be connected to. I know it's kinda janky, but it's the recommended method from the compose team for handling that issue. I've done a search through the project however and the wait-for-it and mvnw files are the only executable files in the environment. Everything else that's not straight data, config, or source code is in the docker containers itself so this type of error should dissapate if you make sure these files are confirmed as exectible for the user running the compose script. 

We generally use the superuser for running these scripts as our runc environment is owned by root. Sorry for the inconvenience here!

**Comment by notxt** [comment]
Hi! Sorry was stuck in meetings all morning 

Thanks for the suggestions! Durp of course it would need execute, I missed that last night 😴 

My current deployment process had been to clone the repo locally (on mac) and then sftp to the EC2 instance. All files are owned by ec2-user. When I look at permissions locally they look good so it's probably the SFTP plugin I'm using for Visual Studios Code 😑 

Gonna clone directly to the box and try again

Thanks for the quick response!
michael

**Comment by notxt** [comment]
Build successful 🎉 

![image](https://user-images.githubusercontent.com/338020/88977047-fa422e00-d271-11ea-8528-923ed4f0210d.png)

Sorry for the lag, kept running out of disk space and needing to up it

You can close this issue if you'd like

Thanks for the help!
michael

**Comment by notxt** [comment]
Closing this cause it's was just my SFTP program messing with permissions 🎉
