### ISSUE TITLE
Question - How to load-balanced on AWS

### ISSUE THREAD

**Issue by notxt** [gt-health/PACER#9]
Hi!

I was wondering if there's a way to move the point the CQL storage at an external DB? Curious because I'd like to run this on AWS as an Elastic Beanstalk application

Also, would I run into other internal state issues if did a multi-instance deployment

thanks!
michael

**Comment by notxt** [comment]
Oh wait, would I just override the environment vars to point at my postgres RDS instance? 🤔 
https://github.com/gt-health/PACER/blob/master/docker-compose.yml#L14

**Comment by MikeRileyGTRI** [comment]
Hello! Yes, you can change the database source by changing all the JDBC environment parameters within docker_compose.yml. There are 3 services that use databases, and they all use jdbc.
JobManagementSystem
CQLStorage
translateconcept.

So yes, your intuition is correct! An external DB can setup for these.

Furthurmore, JobManagementSystem and CQlStorage have a CREATE-DROP schema creation, meaning they can create their own tables and schema once they have a database pointer from the JDBC_URL. translateconcept needs and omop_v5 schema instance.
